### PR TITLE
Initial CI Support

### PR DESCRIPTION
**Pull request by frodofine**
I've enabled Travis-CI and AppVeyor-CI and fixed up some platform related issues tested by these platforms (most Emscripten, which can be a significant pain).

Tested on AppVeyor:

MinGW on 32- and 64-bit systems.

MSVC 2015 on 32- and 64-bit systems.

Tested on Travis:

Default compilation on Linux (64-bit), Emscripten, Clang on Linux, 32-bit on Linux, Clang on MacOSX, and GCC on MacOSX.

### CODE REVIEW

**Comment by gtauriello** [comment]
Changes look good to me. All tests pass, the tests can be run with "ctest" (which will come in handy in the future if we add more tests) and it even supports Emscripten. Cool. Thank you!

Only thing that puzzled me was that Emscripten is ok with htonl in binary_encoder but not with ntohl in binary_decoder? The thing is that htonl and ntohl should be basically the same functions. And the problem with your replacement function is that ntohl is not guaranteed to actually flip the bytes. It will "only" do it when the host machine is little endian (which is the case for most (if not all) hosts and I don't know if we will ever need an Emscripten compilation on a big endian host). Given that I have 0 experience with Emscripten, I don't know if there is any workaround that would still involve calling ntohl/ntohs, but if there is, it would be the preferred solution...

**Comment by frodofine** [comment]
`ntohl` is not the issue, but the conversion from a `char *` array to a `uint32_t*` array. I'm no expert, but I think it is a result of how Emscripten handles memory as it is transpiled into javascript.

**Comment by gtauriello** [comment]
Oh I see. Maybe it just needs some reinterpret_cast there then instead of the C-style cast (I copy/pasted that code from the mmtf-c code). It shouldn't convert anything. It should just "claim" that the pointer is to an uint32_t instead of a char.

**Comment by frodofine** [comment]
I tried that initially, but it not work. I believe it may be due to how points are handled in Emscripten (again, it ends up as Javascript). I'm too lazy to investigate further, but I know there is a possibility that the arrays are padded in a manner that does not allow for the direct conversion.

**Comment by gtauriello** [comment]
If the padding was off, the code wouldn't work I think. Now that I look at the code, the problem might be the constness, which is casted away (unnecessarily probably). So a reinterpret_cast to `const uint32_t` might do the trick. But ok. If that doesn't work, we can just leave it like that for now...

**Comment by frodofine** [comment]
A `reinterpret_cast<uint32_t*>` actually wouldn't compile because you cannot remove `const` unless you use a C-style cast or a `const_cast`, but the issue is above my head and it goes deeper than the scope of this project. Maybe I'll make a post on StackOverflow, it could even be a bug in Emscripten!

**Comment by frodofine** [comment]
It is, in fact, a memory alignment issue (I got a free minute to Google around):

See: [https://github.com/kripken/emscripten/issues/4774](https://github.com/kripken/emscripten/issues/4774)

If I understand that post, the original version is dependant on the x86 architecture, so it could be interesting to see if it works on ARM platforms.

**Comment by gtauriello** [comment]
You misunderstood my proposal: my point was to cast to `const uint32_t*` not to `uint32_t*`. As you correctly pointed out, you cannot remove the `const` but for this call you don't really need to remove it anyways.

So to be precise:
```
void assignBigendian4(void* dst, const char* src) {
    *((uint32_t*)dst) = ntohl(*(reinterpret_cast<const uint32_t*>(src)));
}
void assignBigendian2(void* dst, const char* src) {
    *((uint16_t*)dst) = ntohs(*(reinterpret_cast<const uint16_t*>(src)));
}
```
Compiles for me, but I cannot test whether it works for Emscripten too...

The problem in the kripken post is about loading integers at addresses which are not 4-byte-aligned. Looking at the MMTF specs, I don't think this can happen here...

**Comment by frodofine** [comment]
It does not work, I can investigate further later though.

**Comment by gtauriello** [comment]
Ok fair enough. I guess it's not worth the extra effort to dig deeper. I'm convinced. Don't worry about it.

Please add a comment for the Emscripten workaround to point out that the workaround will "only" work for little endian machines. Other than that, the changes are ok for me.

**Comment by frodofine** [comment]
Emscripten only supports little-endian machines! I've added a comment nonetheless in case this changes in the future. I'm still interested if non-x86 architectures are supported, but that's a subject for a different time.

**Comment by gtauriello** [comment]
Ah ok if Emscripten only supports little endian then there is nothing wrong with your workaround anyways. Still nice to have that comment for picky people like me... ;-)
Thanks. Also since noone is objecting on these changes, I guess I can just approve and merge them.

**Pull request merged**
